  - label: ":ios::mushroom:-RN_69_demo_project"
    command:
      - "nvm install"
      - "./scripts/demo-projects.ios.sh"
    env:
      REACT_NATIVE_VERSION: 0.69.5
    artifact_paths:
      - "/Users/builder/work/coverage/**/*.lcov"
      - "/Users/builder/work/artifacts*.tar.gz"
    agents:
      queue: buildkite-test
